services:
  api:
    build: .
    volumes:
      - ./src:/src
    env_file:
      - .env.local
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    tty: true
    image: postgres:alpine
    volumes:
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - pg-queue-data:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - 5433:5432

  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - 6379:6379

volumes:
  pg-queue-data: {}
